# Generated by Django 5.0.4 on 2024-06-21 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansa_target', '0002_rename_monthlytarget_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
