# Generated by Django 5.0.4 on 2025-01-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansa_target', '0003_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
