# Generated by Django 5.0.4 on 2024-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansaauser',
            name='picture',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
