# Generated by Django 5.0.4 on 2024-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboards',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='billboards',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='billboards',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='billboards',
            name='main_image',
        ),
        migrations.AddField(
            model_name='billboards',
            name='image_1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billboards',
            name='image_2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billboards',
            name='image_3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billboards',
            name='main_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='category',
            field=models.CharField(blank=True, choices=[('free_standing_signs', 'Free standing signs'), ('projecting_signs', 'Projecting signs'), ('wall_signs', 'Wall signs'), ('special_advertisement', 'Special advertisement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='zone',
            field=models.CharField(blank=True, choices=[('normal zone', 'Normal zone'), ('restricted_zone', 'Restricted zone')], max_length=50),
        ),
    ]
