# Generated by Django 5.0.4 on 2024-06-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0002_remove_billboards_image_1_remove_billboards_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboards',
            old_name='image_1_url',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='image_2_url',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='image_3_url',
            new_name='image_3',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='main_image_url',
            new_name='main_image',
        ),
    ]
