# Generated by Django 5.0.4 on 2024-06-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0004_dimensions_alter_billboards_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensions',
            name='category',
            field=models.CharField(blank=True, choices=[('free_standing_signs', 'Free standing signs'), ('projecting_signs', 'Projecting signs'), ('wall_signs', 'Wall signs'), ('special advertisement', 'Special advertisement'), ('billboard designation', 'Billboard Designation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='zone',
            field=models.CharField(blank=True, choices=[('normal zone', 'Normal zone'), ('restricted zone', 'Restricted zone')], max_length=50),
        ),
    ]
