# Generated by Django 5.0.4 on 2024-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0005_alter_dimensions_category_alter_dimensions_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboards',
            name='zone',
            field=models.CharField(blank=True, choices=[('normal zone', 'Normal zone'), ('restricted zone', 'Restricted zone')], max_length=50),
        ),
    ]
