# Generated by Django 5.0.4 on 2024-06-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0006_alter_billboards_zone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zones',
            new_name='SubZones',
        ),
    ]
