# Generated by Django 5.0.4 on 2024-06-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0007_rename_zones_subzones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubZones',
            new_name='Zones',
        ),
        migrations.AlterField(
            model_name='billboards',
            name='zone',
            field=models.CharField(blank=True, choices=[('normal zone', 'Normal zone'), ('restricted_zone', 'Restricted zone')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='category',
            field=models.CharField(blank=True, choices=[('free_standing_signs', 'Free standing signs'), ('projecting_signs', 'Projecting signs'), ('wall_signs', 'Wall signs'), ('special_advertisement', 'Special advertisement'), ('billboard_designation', 'Billboard_Designation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='zone',
            field=models.CharField(blank=True, choices=[('normal zone', 'Normal zone'), ('restricted_zone', 'Restricted zone')], max_length=50),
        ),
    ]
