# Generated by Django 5.0.6 on 2024-07-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0011_alter_billboards_category_alter_dimensions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboards',
            name='actual_dimension',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
