# Generated by Django 5.0.4 on 2024-10-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0012_billboards_actual_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboards',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
