# Generated by Django 5.0.4 on 2025-01-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0014_billboards_payment_date_billboards_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboards',
            old_name='actual_dimension',
            new_name='actual_size',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='city',
            new_name='asset_lga',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='address',
            new_name='asset_street_address',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='phone_number',
            new_name='company_phone',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='image_1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='image_2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='image_3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='asset_name',
            new_name='unique_id',
        ),
        migrations.RemoveField(
            model_name='billboards',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='billboards',
            name='main_image',
        ),
        migrations.AddField(
            model_name='billboards',
            name='asin',
            field=models.CharField(default=True, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='breadth',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='business_category',
            field=models.CharField(choices=[('office_or_shops', 'Office or shops'), ('hotels_or_eateries', 'Hotels or Eateries'), ('parks', 'Parks'), ('hostels', 'Hostels'), ('commercial_banks', 'Commercial Banks'), ('private_microfinance_banks', 'Private/Microfinance Banks')], default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='business_type',
            field=models.CharField(choices=[('commercial_business', 'Commercial business')], default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='illumination_type',
            field=models.CharField(choices=[('none', 'None'), ('external', 'External'), ('internal', 'Internal')], default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='length',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='no_of_faces',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('multiple', 'Multiple')], default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='sign_format',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='sign_type',
            field=models.CharField(blank=True, choices=[('walldrapes', 'Walldrapes'), ('projecting_signs', 'Projecting signs'), ('wall_canopy_roof_signs', 'Wall/Canopy/Roof Signs'), ('neon_signs', 'Neon signs'), ('48_sheets', '48 sheets'), ('96_sheets', '96 Sheets'), ('bridge_panel', 'Bridge panel'), ('overhead_gantries', 'Overhead Gantries'), ('lamp_posts', 'Lamp posts'), ('unipoles', 'Unipoles'), ('led_screens_filling_stations', 'LED Screens (Filling stations)')], max_length=50),
        ),
        migrations.AddField(
            model_name='billboards',
            name='signage_type',
            field=models.CharField(blank=True, choices=[('first_party', 'First Party'), ('third_party', 'Third Party')], max_length=50),
        ),
    ]
