# Generated by Django 5.0.4 on 2025-02-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0015_rename_actual_dimension_billboards_actual_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboards',
            name='category',
        ),
    ]
