# Generated by Django 5.0.4 on 2025-02-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0017_alter_billboards_breadth_alter_billboards_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboards',
            name='business_category',
            field=models.CharField(choices=[('Office or Shops', 'Office or Shops'), ('Hotels or Eateries', 'Hotels or Eateries'), ('Parks', 'Parks'), ('Hostels', 'Hostels'), ('Commercial Banks', 'Commercial Banks'), ('Private/Microfinance Banks', 'Private/Microfinance Banks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='business_type',
            field=models.CharField(choices=[('Commercial Business', 'Commercial Business')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='illumination_type',
            field=models.CharField(choices=[('None', 'None'), ('External', 'External'), ('Internal', 'Internal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='no_of_faces',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Multiple', 'Multiple')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='sign_format',
            field=models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='sign_type',
            field=models.CharField(blank=True, choices=[('Walldrapes', 'Walldrapes'), ('Projecting Signs', 'Projecting Signs'), ('Wall/Canopy/Roof Signs', 'Wall/Canopy/Roof Signs'), ('Neon Signs', 'Neon Signs'), ('48 Sheets', '48 Sheets'), ('96 Sheets', '96 Sheets'), ('Bridge panel', 'Bridge panel'), ('Overhead Gantries', 'Overhead Gantries'), ('Lamp Posts', 'Lamp Posts'), ('unipoles', 'Unipoles'), ('LED Screens (Filling stations)', 'LED Screens (Filling stations)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='signage_type',
            field=models.CharField(blank=True, choices=[('First Party', 'First Party'), ('Third Party', 'Third Party')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='vacancy',
            field=models.CharField(blank=True, choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied')], default='vacant', max_length=20),
        ),
    ]
