# Generated by Django 5.0.4 on 2025-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0018_alter_billboards_business_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountPerSqFt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_sq_ft', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
