# Generated by Django 5.0.4 on 2025-07-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0019_amountpersqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboards',
            name='sign_type',
            field=models.CharField(blank=True, choices=[('Walldrapes', 'Walldrapes'), ('Projecting Signs', 'Projecting Signs'), ('Wall/Canopy/Roof Signs', 'Wall/Canopy/Roof Signs'), ('Neon Signs', 'Neon Signs'), ('48 Sheets', '48 Sheets'), ('96 Sheets', '96 Sheets'), ('Bridge panel', 'Bridge panel'), ('Overhead Gantries', 'Overhead Gantries'), ('Lamp Posts', 'Lamp Posts'), ('Unipoles', 'Unipoles'), ('LED Screens (Filling stations)', 'LED Screens (Filling stations)')], max_length=50),
        ),
    ]
